name: lakukan_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.5
  intl: ^0.18.1
  photo_view: ^0.12.0
  cached_network_image: ^3.1.0
  loading_indicator: ^3.1.1
  carousel_slider: ^4.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - lib/app/widget/app/assets/images/
  - lib/app/widget/app/assets/images/icons/
  - lib/app/widget/app/assets/images/icons/banks/
  - lib/app/widget/app/assets/images/icons/ewallets/
  - lib/app/widget/app/assets/images/icons/flags/
  - lib/app/widget/app/assets/images/icons/payments/
  - lib/app/widget/app/assets/images/icons/menus/
  - lib/app/widget/app/assets/images/icons/social_medias/
  - lib/app/widget/app/assets/images/icons/other/
  - lib/app/widget/app/assets/images/illustrations/
  - lib/app/widget/app/assets/images/illustrations/onboarding/

